export const CATEGORIES = [
  'Groceries',
  'Transport',
  'Entertainment',
  'Subscriptions',
  'Utilities',
  'Rent',
  'Clothing',
  'Health',
  'Education',
  'Dining Out',
  'Savings',
  'Income',
  'Other',
];